version: "3.4"
services:
  bridge-server:
    build: 
      context: .
      dockerfile: bridge.dockerfile
      args:
        GOPATH: /gopath
    restart: always
    ports:
      - 9090:9090
      - 2200:2200
    environment:
      - GOPATH=/gopath
